'use client'

import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { ChefHat, Check, Clock3, MapPin, Plus, ShoppingBag } from 'lucide-react'

const initialOrders = [{ id: '#1042', customer: 'Luna Martins', items: '2x Cappuccino, 1x Pão de queijo', total: 'R$ 28,50', status: 'aberto', time: 'Agora' }, { id: '#1041', customer: 'Theo Alves', items: '1x Latte de caramelo, 1x Cookie', total: 'R$ 24,00', status: 'preparo', time: 'há 4 min' }, { id: '#1040', customer: 'Nina Costa', items: '2x Mocha, 1x Bolo de cenoura', total: 'R$ 31,00', status: 'pronto', time: 'há 8 min' }]
const columns = [{ key: 'aberto', label: 'Novos pedidos', icon: ShoppingBag }, { key: 'preparo', label: 'Em preparo', icon: ChefHat }, { key: 'pronto', label: 'Prontos', icon: Check }]
export function OrdersBoard() {
  const [orders, setOrders] = useState(initialOrders)
  function advance(id: string) { setOrders((all) => all.map((o) => o.id === id ? { ...o, status: o.status === 'aberto' ? 'preparo' : 'pronto' } : o)) }
  return <div className="flex flex-col gap-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Quarta-feira, 31 de agosto</p><h1 className="font-display text-3xl font-800 text-foreground">Pedidos abertos</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhe o ritmo da cafeteria em tempo real.</p></div><Button><Plus data-icon="inline-start" /> Novo pedido</Button></div><div className="grid gap-4 lg:grid-cols-3">{columns.map(({ key, label, icon: Icon }) => <section key={key} className="flex min-h-80 flex-col gap-3 rounded-2xl bg-secondary/60 p-3"><div className="flex items-center justify-between px-2 py-1"><div className="flex items-center gap-2 font-display font-700"><Icon className="size-4 text-primary" />{label}</div><Badge variant="secondary">{orders.filter((o) => o.status === key).length}</Badge></div>{orders.filter((o) => o.status === key).map((order) => <Card key={order.id} className="rounded-xl border-border/70 shadow-sm"><CardHeader className="flex flex-row items-start justify-between gap-3 pb-3"><div><CardTitle className="font-display text-lg">{order.id}</CardTitle><p className="text-sm font-semibold text-foreground">{order.customer}</p></div><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3" />{order.time}</span></CardHeader><CardContent className="flex flex-col gap-3 pt-0"><p className="text-sm leading-6 text-muted-foreground">{order.items}</p><div className="flex items-center justify-between border-t border-border pt-3"><span className="font-display font-700 text-primary">{order.total}</span>{key !== 'pronto' && <Button size="sm" variant="outline" onClick={() => advance(order.id)}>{key === 'aberto' ? 'Preparar' : 'Pronto'}</Button>}</div></CardContent></Card>)}</section>)}</div><div className="flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3" /> Dados demonstrativos para visualização do protótipo</div></div>
}
